@startuml
!theme plain
top to bottom direction
skinparam linetype polyline

class node1 as "src/extension.ts" {
   JsonSchemaBuilderProvider:
   JsonSchemaRendererProvider:
   vscode:
}
class node2 as "src/jsonSchemaBuilderProvider.ts" {
   JsonSchemaBuilderProvider:
   JsonSchemaRendererProvider:
   closeStdEditor:
   debounce:
   getContentAsJson:
   getDefault:
   getHtmlForWebview:
   openStdEditor:
   vscode:
}
class node3 as "src/jsonSchemaRendererProvider.ts" {
   JsonSchemaRendererProvider:
   getHtmlForWebview:
   vscode:
}
class node4 as "src/utils.ts" {
   closeStdEditor:
   getContentAsJson:
   getDefault:
   getHtmlForWebview:
   openStdEditor:
   vscode:
}

node1   <-[#595959,plain]-  node2
node1   <-[#595959,plain]-  node3
node2   <-[#595959,plain]-  node3
node2   <-[#595959,plain]-  node4
node2   <-[#595959,plain]-  node4
node2   <-[#595959,plain]-  node4
node2   <-[#595959,plain]-  node4
node2   <-[#595959,plain]-  node4
node3   <-[#595959,plain]-  node4
@enduml